### ISSUE TITLE
Translations have not been updated

### ISSUE THREAD

**Issue by goeranu** [fedora-selinux/selinux#43]
There is a domain _selinux (policycoreutils)_ which appears to come from this project.  But apparently, something is broken when the finished translations are to be fed back.  The files in the [policycoreutils/po](https://github.com/fedora-selinux/selinux/tree/master/policycoreutils/po) directory have not been updated in 4 years.

**Comment by bachradsusi** [comment]
You are right that the process around updating translations is broken now.

The last time when translations were updated was in Fedora 25/26 - https://github.com/fedora-selinux/selinux/commit/be955a4daf0598dbce8881c5dbab23b0cb1a6322 - in policycoreutils-2.5-18.fc26. Unfortunately they were not applied after rebase to policycoreutils-2.6.

Since policycoreutils were split into independent parts and I need to find out how to apply current source .pot file on them. I guess that it would be enough to change POTFILES path in Makefile.

Anyway, during next week I'll try to update translations in f26 branch as this is probably  most accurate version to the state in zanata, then I'll try to merge existing translations with the new structure and I'll upload new pot files.

**Comment by bachradsusi** [comment]
I split `policycoreutils.pot` into `policycoreutils.pot` `python.pot` `gui.pot` and `sandbox.pot`. You can find them on zanata - https://fedora.zanata.org/iteration/view/selinux/master/documents?dswid=-8666

At the same time, I've updated `README.translation` if Fedora dist-git so that it explains how to update, download and created need files from zanata - https://src.fedoraproject.org/rpms/policycoreutils/c/1cf65c551e9a1d2fa2f129b265cd544ac40a2681?branch=master

And all translations in this repository should be up-to-date to `master` zanata branch https://fedora.zanata.org/iteration/view/selinux/master?dswid=-8666
